image: ikus060/python:debian9-py3

stages:
- test
- package
- publish
- deploy
- downstream

#
# Test Stage
#
.tox:  &tox
  image: ikus060/python:${IMAGE}
  stage: test
  variables:
    IMAGE: debian10-py3
    TOXENV: $CI_JOB_NAME
  before_script:
  - command -v apt && apt -yq update && apt install -yq rdiff-backup libldap2-dev libsasl2-dev
  - command -v yum && yum install -y epel-release && yum install -y rdiff-backup openldap-devel
  script:
  - export TOXENV=${TOXENV:-$CI_JOB_NAME}
  - echo TOXENV=$TOXENV
  - tox
  artifacts:
    paths:
    - coverage-*.xml
    - nosetests-*.xml
    expire_in: 1 day

# FIXME Downgrade setuptools for this target.
# This is broken because of setuptools 46.0.0
.py3-jinja26: 
  <<: *tox

py3-jinja27: 
  <<: *tox

py3-jinja28: 
  <<: *tox

py3-jinja29: 
  <<: *tox

py3-jinja210: 
  <<: *tox

py3-cherrypy18: 
  <<: *tox

debian9-py3-cherrypy35-jinja28: 
  <<: *tox
  variables:
    IMAGE: debian9-py3
    TOXENV: py3-cherrypy35-jinja28

debian10-py3-cherrypy8-jinja210: 
  <<: *tox
  variables:
    IMAGE: debian10-py3
    TOXENV: py3-cherrypy8-jinja28
  
debian10-py3-rdiff-backup2:
  <<: *tox
  variables:
    IMAGE: debian10-py3
    TOXENV: py3-cherrypy8-jinja210
  before_script:
  - apt-get update
  - apt -y install librsync-dev libldap2-dev libsasl2-dev
  - pip3 install rdiff-backup
  - tox

debian11-py3-cherrypy8-jinja211: 
  <<: *tox
  variables:
    IMAGE: debian11-py3
    TOXENV: py3-cherrypy8-jinja211

centos7-py3-cherrypy18-jinja210:
  <<: *tox
  variables:
    IMAGE: centos7-py3
    TOXENV: py3-cherrypy18-jinja210
  allow_failure: true

centos8-py3-cherrypy18-jinja210:
  <<: *tox
  variables:
    IMAGE: centos8-py3
    TOXENV: py3-cherrypy18-jinja210
  
package:py3: 
  stage: package
  script:
  - pip3 install wheel
  - python3 setup.py sdist bdist_wheel
  dependencies: []
  artifacts:
    paths:
    - dist/*.whl

package:debian: 
  stage: package
  image: ikus060/python:debian11-py3
  script: |
    export BUILDDEPS=$(dpkg-checkbuilddeps 2>&1 | sed 's/dpkg-checkbuilddeps:\serror:\sUnmet build dependencies: //g' | sed 's/[\(][^)]*[\)] //g')
    echo BUILDDEPS=$BUILDDEPS
    apt update && apt -y install $BUILDDEPS
    dpkg-buildpackage -b
  dependencies: []
  artifacts:
    paths:
    - ../rdiffweb*.dsc
    - ../rdiffweb*.tar.xz
    - ../rdiffweb*.deb
    - ../rdiffweb*.changes

publish:sonar:master:
  stage: publish
  image: ikus060/sonar-runner
  only:
  - master
  script:
  - sonar-runner -X -Dsonar.python.coverage.reportPath=coverage-*.xml -Dsonar.python.xunit.reportPath=nosetests-py3-cherrypy18.xml -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.exclusions=rdiffweb/controller/tests/**,rdiffweb/core/tests/**,rdiffweb/test.py -Dsonar.sources=.

publish:sonar:dev:
  stage: publish
  image: ikus060/sonar-runner
  script:
  - sonar-runner -X -Dsonar.python.coverage.reportPath=coverage-*.xml -Dsonar.python.xunit.reportPath=nosetests-py3-cherrypy18.xml -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=$CI_PROJECT_NAME-dev -Dsonar.exclusions=rdiffweb/controller/tests/**,rdiffweb/core/tests/**,rdiffweb/test.py -Dsonar.sources=.

publish_nexus:
  stage: publish
  script:
  - pip3 install wheel twine --upgrade
  - twine upload dist/* -u $NEXUS_USR -p $NEXUS_PWD --repository-url $NEXUS_PYPI_URL

publish_pypi:
  stage: publish
  only:
  - tags
  script:
  - pip3 install wheel twine --upgrade
  - twine upload dist/* -u $PYPI_USR -p $PYPI_PWD
  
deploy_rdiffweb_demo:
  stage: deploy
  environment:
    name: demo
    url: https://rdiffweb-demo.ikus-soft.com/
  script:
  - export RDIFFWEB_VERSION=$(python3 setup.py --version | tail -n 1)
  - echo RDIFFWEB_VERSION=$RDIFFWEB_VERSION
  # Call ansible
  - curl -X POST -F token=36bae86778d901fc6b2d6453a41844 -F "ref=master" -F "variables[RDIFFWEB_VERSION]=$RDIFFWEB_VERSION" https://gitlab.com/api/v4/projects/18716492/trigger/pipeline

bump_minarca_version:
  stage: downstream
  only:
  - tags
  script:
  - export RDIFFWEB_VERSION=$(python3 setup.py --version | tail -n 1)
  - echo RDIFFWEB_VERSION=$RDIFFWEB_VERSION
  # configure git & ssh
  - git config --global user.email "robot@ikus-soft.com"
  - git config --global user.name "IKUS Soft robot"
  - mkdir ~/.ssh && chmod 0700 ~/.ssh
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  - echo "$GITLAB_MINARCA_DEPLOY_KEY" >> ~/.ssh/id_rsa
  - chmod 0600 ~/.ssh/id_rsa
  # Checkout minarca and upgrade version.
  - git clone git@gitlab.com:ikus-soft/minarca.git
  - cd minarca/
  - sed -i -e "s/\"rdiffweb==.*\"/\"rdiffweb==$RDIFFWEB_VERSION\"/g" minarca-server/setup.py
  - git add minarca-server/setup.py
  - git commit -m "Bump rdiffweb to v$RDIFFWEB_VERSION"
  - git push origin master
  